version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: google-rag-backend
    restart: unless-stopped
    ports:
      - "7000:5000"
    volumes:
      - ./documents_storage:/app/documents_storage
    environment:
      FLASK_ENV: production
      DOCUMENTS_STORAGE: /app/documents_storage
      # Google / Gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GENERATION_API_KEY: ${GENERATION_API_KEY}
      FILE_SEARCH_STORE_NAME: ${FILE_SEARCH_STORE_NAME}

      # Modell & Chunking
      DEFAULT_MODEL: ${DEFAULT_MODEL}
      CHUNK_SIZE: ${CHUNK_SIZE}
      CHUNK_OVERLAP_PERCENT: ${CHUNK_OVERLAP_PERCENT}
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: google-rag-frontend
    restart: unless-stopped
    ports:
      - "7001:80"
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
